my_list = []                       
my_list.append(10)                 
my_list.append(20)
my_list.append(30)
my_list.append(40)
my_list.insert(1, 15)               
my_list.extend([50, 60, 70])        
my_list.pop()                       
my_list.sort()                      
print("Final list:", my_list)
print("Index of 30:", my_list.index(30))  
my_list.reverse()      
print("Reversed list:", my_list)
print("Largest number:", max(my_list))
print("Smallest number:", min(my_list))
